[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
solc = "0.8.34"

[profile.default.optimizer_details]
yul = true

fs_permissions = [{ access = "read", path = "script/data/prompt_seed.json"}]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
